[funfacts]
title = "xaufe.edu.cn"
url = "https://www.xaufe.edu.cn/index.htm"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[notice]
title = "xaufe notice"
url = "https://www.xaufe.edu.cn/xxgg1.htm"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
